### ISSUE TITLE
Footer shows © Bitcoin Project

### ISSUE THREAD

**Issue by jhult** [dash-docs/dash-docs.github.io#3]
Copyright should be **The Dash Network** not **Bitcoin Project**.

**Comment by dash-docs** [comment]
The site is actually a fork of bitcoin.org and is not officially associated with Dash.  The bitcoin copyright was left intact (as it is in Dash Core source - [example](https://github.com/dashpay/dash/blob/master/src/validation.h#L1-#L3)). Not an expert on these things and not exactly sure what, if anything, should be there.  Glad to change it if there is a clear answer.
